postgresql:
  enabled: false
  install: false
service:
  enabled: true
  name: web
  type: ClusterIP
  url: https://ridebeep.app/socket.io
  externalPort: 3000
  internalPort: 3000
livenessProbe:
  path: "/socket.io"
  initialDelaySeconds: 20
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "tcpSocket"
readinessProbe:
  path: "/socket.io"
  initialDelaySeconds: 20
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "tcpSocket"
